name: form_utility
description: "This package helps to handle form logics with more ease."
homepage: https://github.com/Ashkan-Oliaie/flutter_form_utility
version: 0.0.2

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
