name: form_utility
description: "Form Utility: A Dart package designed to simplify form logic handling. Ideal for Flutter developers seeking to streamline form validation and improve code readability."
homepage: https://github.com/Ashkan-Oliaie/flutter_form_utility
version: 0.0.9

environment:
  sdk: '>=3.1.3<4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
